require("core.plugin_config.nightfox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.coc")
require("core.plugin_config.airline")
